### ISSUE TITLE
ReadTimeout: HTTPConnectionPool(host='articlemeta-restfulapi', port=8000): Read timed out. (read timeout=3)

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/opac_proc#300]
Deve ser avaliado o uso da interface Thrift ao invés da RESTFul para esse caso de uso.

https://sentry.scielo.org/sentry/homologprocscielobr/issues/13544/

```
ReadTimeout: HTTPConnectionPool(host='articlemeta-restfulapi', port=8000): Read timed out. (read timeout=3)
(5 additional frame(s) were not displayed)
...
  File "requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "raven/breadcrumbs.py", line 326, in send
    resp = real_send(self, request, *args, **kwargs)
  File "requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)

HTTPConnectionPool(host='articlemeta-restfulapi', port=8000): Read timed out. (read timeout=3)
```

**Comment by jfunez** [comment]
Trocando o cliente REstful para o Thrift do ArticleMeta API melhorou o despempenho porém ainda temos erros de timout consultando os identifiers:
```
Traceback (most recent call last):
  File "manage.py", line 435, in <module>
    manager.run()
  File "/usr/local/lib/python2.7/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/local/lib/python2.7/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 183, in process_ids
    task_call_data_retriver_by_model(model='article', force_serial=True)
  File "/app/opac_proc/source_sync/ids_data_retriever_jobs.py", line 66, in task_call_data_retriver_by_model
    retriever_instance.run_serial_for_all()
  File "/app/opac_proc/source_sync/ids_data_retriever.py", line 122, in run_serial_for_all
    for identifier_doc in identifiers:
  File "/app/opac_proc/extractors/source_clients/amapi_wrapper/custom_amapi_client.py", line 43, in get_articles_identifiers
    for obj in objs:
  File "/usr/local/lib/python2.7/site-packages/articlemeta/client.py", line 1083, in documents
    extra_filter=extra_filter
  File "/usr/local/lib/python2.7/site-packages/articlemeta/client.py", line 646, in dispatcher
    response = getattr(cl, func)(*args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/thriftpy/thrift.py", line 198, in _req
    return self._recv(_api)
  File "/usr/local/lib/python2.7/site-packages/thriftpy/thrift.py", line 210, in _recv
    fname, mtype, rseqid = self._iprot.read_message_begin()
  File "thriftpy/protocol/cybin/cybin.pyx", line 429, in cybin.TCyBinaryProtocol.read_message_begin (thriftpy/protocol/cybin/cybin.c:6325)
  File "thriftpy/protocol/cybin/cybin.pyx", line 60, in cybin.read_i32 (thriftpy/protocol/cybin/cybin.c:1546)
  File "thriftpy/transport/buffered/cybuffered.pyx", line 65, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.c_read (thriftpy/transport/buffered/cybuffered.c:1881)
  File "thriftpy/transport/buffered/cybuffered.pyx", line 69, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.read_trans (thriftpy/transport/buffered/cybuffered.c:1948)
  File "thriftpy/transport/cybase.pyx", line 61, in thriftpy.transport.cybase.TCyBuffer.read_trans (thriftpy/transport/cybase.c:1472)
  File "/usr/local/lib/python2.7/site-packages/thriftpy/transport/socket.py", line 108, in read
    buff = self.sock.recv(sz)
socket.timeout: timed out
```

**Comment by jfunez** [comment]
para reproducir o erro:
```python
from articlemeta.client import ThriftClient
client = ThriftClient()
client.documents(
            collection='scl', 
            only_identifiers=True)
```

**Comment by jfunez** [comment]
tracebacks de cliente e servidor thrift:

### Traceback que aparece depois de alguns segundos de inciar a extração de identificadores.

#### Comando:
`/app/opac_proc/python manage.py process_ids`

#### Timestamp: 2018-06-22 14:35:34,479

```
Traceback (most recent call last):
  File "manage.py", line 435, in <module>
    manager.run()
  File "/usr/local/lib/python2.7/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/local/lib/python2.7/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 183, in process_ids
    task_call_data_retriver_by_model(model='article', force_serial=True)
  File "/app/opac_proc/source_sync/ids_data_retriever_jobs.py", line 66, in task_call_data_retriver_by_model
    retriever_instance.run_serial_for_all()
  File "/app/opac_proc/source_sync/ids_data_retriever.py", line 122, in run_serial_for_all
    for identifier_doc in identifiers:
  File "/app/opac_proc/extractors/source_clients/amapi_wrapper/custom_amapi_client.py", line 43, in get_articles_identifiers
    for obj in objs:
  File "/usr/local/lib/python2.7/site-packages/articlemeta/client.py", line 1083, in documents
    extra_filter=extra_filter
  File "/usr/local/lib/python2.7/site-packages/articlemeta/client.py", line 646, in dispatcher
    response = getattr(cl, func)(*args[1:], **kwargs)
  File "/usr/local/lib/python2.7/site-packages/thriftpy/thrift.py", line 198, in _req
    return self._recv(_api)
  File "/usr/local/lib/python2.7/site-packages/thriftpy/thrift.py", line 210, in _recv
    fname, mtype, rseqid = self._iprot.read_message_begin()
  File "thriftpy/protocol/cybin/cybin.pyx", line 429, in cybin.TCyBinaryProtocol.read_message_begin (thriftpy/protocol/cybin/cybin.c:6325)
  File "thriftpy/protocol/cybin/cybin.pyx", line 60, in cybin.read_i32 (thriftpy/protocol/cybin/cybin.c:1546)
  File "thriftpy/transport/buffered/cybuffered.pyx", line 65, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.c_read (thriftpy/transport/buffered/cybuffered.c:1881)
  File "thriftpy/transport/buffered/cybuffered.pyx", line 69, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.read_trans (thriftpy/transport/buffered/cybuffered.c:1948)
  File "thriftpy/transport/cybase.pyx", line 61, in thriftpy.transport.cybase.TCyBuffer.read_trans (thriftpy/transport/cybase.c:1472)
  File "/usr/local/lib/python2.7/site-packages/thriftpy/transport/socket.py", line 108, in read
    buff = self.sock.recv(sz)
socket.timeout: timed out
```

### Traceback que aparece no container do thriftserver, no momento do erro anterior
#### Timestamp: 6/22/2018 2:37:59
```
ERROR:thriftpy.server:[Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/thriftpy/server.py", line 95, in handle
    self.processor.process(iprot, oprot)
  File "/usr/local/lib/python3.5/site-packages/thriftpy/thrift.py", line 307, in process
    self.send_result(oprot, api, result, seqid)
  File "/usr/local/lib/python3.5/site-packages/thriftpy/thrift.py", line 278, in send_result
    result.write(oprot)
  File "/usr/local/lib/python3.5/site-packages/thriftpy/thrift.py", line 153, in write
    oprot.write_struct(self)
  File "thriftpy/protocol/cybin/cybin.pyx", line 477, in cybin.TCyBinaryProtocol.write_struct (thriftpy/protocol/cybin/cybin.c:7205)
  File "thriftpy/protocol/cybin/cybin.pyx", line 474, in cybin.TCyBinaryProtocol.write_struct (thriftpy/protocol/cybin/cybin.c:7127)
  File "thriftpy/protocol/cybin/cybin.pyx", line 212, in cybin.write_struct (thriftpy/protocol/cybin/cybin.c:3342)
  File "thriftpy/protocol/cybin/cybin.pyx", line 356, in cybin.c_write_val (thriftpy/protocol/cybin/cybin.c:5142)
  File "thriftpy/protocol/cybin/cybin.pyx", line 115, in cybin.write_list (thriftpy/protocol/cybin/cybin.c:2115)
  File "thriftpy/protocol/cybin/cybin.pyx", line 362, in cybin.c_write_val (thriftpy/protocol/cybin/cybin.c:5200)
  File "thriftpy/protocol/cybin/cybin.pyx", line 212, in cybin.write_struct (thriftpy/protocol/cybin/cybin.c:3342)
  File "thriftpy/protocol/cybin/cybin.pyx", line 353, in cybin.c_write_val (thriftpy/protocol/cybin/cybin.c:5112)
  File "thriftpy/protocol/cybin/cybin.pyx", line 122, in cybin.write_string (thriftpy/protocol/cybin/cybin.c:2202)
  File "thriftpy/transport/buffered/cybuffered.pyx", line 55, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.c_write (thriftpy/transport/buffered/cybuffered.c:1753)
  File "thriftpy/transport/buffered/cybuffered.pyx", line 80, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.c_flush (thriftpy/transport/buffered/cybuffered.c:2147)
  File "/usr/local/lib/python3.5/site-packages/thriftpy/transport/socket.py", line 129, in write
    self.sock.sendall(buff)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by jfunez** [comment]
podemos fechar, já que não temos mais dependência de conectar com api rest do AM. Agora é só com Thrift.
