### ISSUE TITLE
[BUG] Erro durante o processamento do am2opac para coleção scl

### ISSUE THREAD

**Issue by brunousml** [scieloorg/opac_proc#54]
Ao executar o processamento recebo o erro:

```
Traceback (most recent call last):
  File "am2opac.py", line 742, in <module>
    main(sys.argv)
  File "am2opac.py", line 731, in main
    return run(options, pool)
  File "am2opac.py", line 647, in run
    bulk(options, pool)
  File "am2opac.py", line 597, in bulk
    pool.map(process_article, pissns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
pymongo.errors.CursorNotFound: Cursor not found, cursor id: 149418961290
```

**Comment by jamilatta** [comment]
@brunousml 

irei fechar esse ticket, como havia comentado contigo, esse script não é tolerante a falhas e nem será já que iremos trabalhar com o opac_proc_web que contém esse recurso.

Portanto, não faz sentido melhorarmos o am2opac.py.

**Comment by brunousml** [comment]
👍
